import "@/styles/globals.css";

import { type Metadata } from "next";
import { Courier_Prime, Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const courier = Courier_Prime({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-courier-prime",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${courier.variable}`}>
      <body className="min-h-screen bg-primary text-text-main">{children}</body>
    </html>
  );
}
